### ISSUE TITLE
Top level language folders

### ISSUE THREAD

**Issue by kurmachu** [NexTre-dev/retro-gadgets-docs#20]
For the sake of both organization and to allow me to add a language select to the viewer, we should switch to top level language folders with full language names. (As opposed to the current convention of translating each folder individually with a language code suffix)

If this gets approved I can do the refactoring, we'd just have to notify the people currently working on languages.

**Comment by thekifake** [comment]
I think this is probably a good idea, but things should settle first so rearranging things will be easier :)

**Comment by kurmachu** [comment]
I'm okay with rewriting PRs for language contributions but sadly only repository owners can do that

**Comment by kurmachu** [comment]
It looks like language translators don't have any pending commits right now, perhaps this is a good time? What do you think, @NexTre-dev?

**Comment by NexTre-dev** [comment]
I think you can do it right now if no one is working on other languages

**Comment by kurmachu** [comment]
Closed as of #22
