### ISSUE TITLE
Missing licence

### ISSUE THREAD

**Issue by kurmachu** [NexTre-dev/retro-gadgets-docs#26]
We here at [the documentation viewer project](https://github.com/kurmachu/retro-docs-site) rely on this project for, well, the actual documentation! Unfortunately, without a licence, technically default copyright applies and no derivative works can be made. Please add a licence, so that we may determine if the viewer is in violation. Additionally, adding a license will allow the viewer project to also set a licence.

**Comment by NexTre-dev** [comment]
Will do as soon as GitHub lets me sign in on a browser (apparently I forgot my password)

**Comment by NexTre-dev** [comment]
I added one
