### ISSUE TITLE
Address new devices

### ISSUE THREAD

**Issue by thekifake** [NexTre-dev/retro-gadgets-docs#28]
ROM, SecurityChip, Wifi, FlashMemory, and fonts have been added in the latest update. Documentation needs to be written for them.

**Comment by kurmachu** [comment]
I can probably do this by the end of tomorrow

**Comment by thekifake** [comment]
Working on [misc components](https://github.com/thekifake/retro-gadgets-docs/tree/additional-components/en/docs/modules/misc) right now.

**Comment by kurmachu** [comment]
I will do inputs and the event system in CPU

**Comment by kurmachu** [comment]
Done! #29
