### ISSUE TITLE
Apparently the keyboard chip has events now

### ISSUE THREAD

**Issue by kurmachu** [NexTre-dev/retro-gadgets-docs#37]
Can someone investigate how it works and update the page?
![image](https://user-images.githubusercontent.com/31492625/206913205-20cc4ade-e858-4110-83c8-67c768192580.png)
https://docs.retrogadgets.game/api/modules/KeyboardChip.html

**Comment by AlvinIsCrack** [comment]
To use any event of a module (if it has any), you first need to make the CPU listens for any event coming from the module you want to use.
For that, you need to go to the **EventChannels** page in the **properties menu** in the multitool when selecting the CPU. There, you select the index in the array you want to set the listener for the module, and then select the module itself.

**EventChannels** > **1** > **KeyboardChip0** (for example)

Then, in the CPU code itself (the one that has the listener set, obviously), you *HAVE TO DEFINE A FUNCTION* that will be called when an **EventChannels** receives a **MESSAGE*.
How's that?

**Every event needs to be settled in a eventChannel function**, that will be automatically called when the module linked sends a message.
In this case, when you have a module settled in index 1 in the EventChannels of your CPU, you define a function like this:

`function eventChannel1(sender, response)
end`

This **HAVE** to be the head of the function for make it work.
Notice the use of lowercase at the first character, and the **1 that represents the index of the EventChannels that we're refering to**.
When a message is received by an EventChannel, it sends two arguments to the function:

**sender: the module class of the object that sent rhe event**
**response: the object that has the body of the event itself, with the properties and such...**

So, if you define an eventChannel1 that listens for a KeyboardChip module, the only event that could be received is an **KeyboardChipEvent**.
**The response body will have the properties shown on the doc, like:**

— response.Buttondown: boolean
— response.InputName: InputName (a string with the name of the key being pressed)
— etc...

Hope this helps!!
Srry if you don't understand some parts, I'm bad explaining, as I don't speak english natively

**Comment by kurmachu** [comment]
Yes, we already have an explanation of events (under CPU), I meant this specific case of the keyboard chip event.

**Comment by kurmachu** [comment]
We have new info! You do not need to have a key bound, and key presses do not backsend events. We just need someone to write these.
